blog_django/apps/post/urls.py
# blog_django/apps/post/urls.py
from django.urls import path
import apps.post.views as views
app_name = 'post'

urlpatterns = [
# Como cada post tiene un uuid, deberiamos usar un slug en lugar de el uuid como parametro
# Un slug es una cadena de texto que identifica de manera unica un recurso
# Pero a diferencia de un uuid, un slug es mas facil de recordar y de escribir
# En este caso, un post podria tener un slug que sea el titulo del post
# TODO: Cambiar para recibir un parametro de tipo <slug:slug>
    path('posts/', views.PostListView.as_view(), name="post_list"),
    path('posts/create', views.PostCreateView.as_view(), name="post_create"),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(),
    name="post_detail"),
    path('posts/<slug:slug>/update', views.PostUpdateView.as_view(),
    name="post_update"),
    path('posts/<slug:slug>/delete', views.PostDeleteView.as_view(),
    name="post_delete"),
]

"""
post_list: URL para listar los posts.
post_create: URL para crear un nuevo post.
post_detail: URL para ver un post en detalle.
post_update: URL para actualizar un post.
post_delete: URL para eliminar un post.
"""

#TODO: en admin, crear post

blog_django/apps/user/urls.py
# blog_django/apps/user/urls.py
from django.urls import path
import apps.user.views as views

app_name = 'user'

urlpatterns = [
    path('users/profile/', views.UserProfileView.as_view(), name="user_profile"),
    path('auth/register/', views.RegisterView.as_view(), name="auth_register"),
    path('auth/login/', views.LoginView.as_view(), name="auth_login"),
    path('auth/logout/', views.LogoutView.as_view(), name="auth_logout"),


]

blog_django/blog_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog_django.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
path('', include('apps.user.urls')),
path('', include('apps.post.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    # Sirviendo archivos estáticos
    urlpatterns += static(settings.STATIC_URL,      document_root=settings.STATIC_ROOT)
    # Sirviendo archivos media
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_django/templates/components/ui/navbar.html
<!-- blog_django\templates\components\ui\navbar.html -->
<nav>
    <ul class="flex gap-4">
        <li><a href="{% url 'home' %}">Inicio</a></li>
        <li>
            <a href="{% url 'post:post_detail' slug='el-inicio-de-la-ia' %}">Ver Post</a>
        </li>
        <li><a href="{% url 'user:user_profile' %}">Perfil</a></li>
        <li><a href="{% url 'user:auth_login' %}">Iniciar sesión</a></li>
        <li><a href="{% url 'user:auth_register' %}">Registrarse</a></li>
    </ul>
</nav>


<nav>
    <ul class="flex gap-4">
        {% if user.is_authenticated %}
        {% if user.is_collaborator %}
        <li><a href="{% url 'post:post_create' %}">Publicar</a></li>
        {% endif %}
        <li><a href="{% url 'user:user_profile' %}">Perfil</a></li>
        <li>
            <form method="post" action="{% url 'user:auth_logout' %}">
                {% csrf_token %}
                <button type="submit">Cerrar sesión</button>
            </form>
        </li>
        {% else %}
        <li><a href="{% url 'user:auth_login' %}">Iniciar sesión</a></li>
        <li><a href="{% url 'user:auth_register' %}">Registrarse</a></li>
        {% endif %}
    </ul>
</nav>


<!--
Nota:
Hemos definido un bloque condicional para mostrar el enlace de Publicar solo si el usuario es un colaborador.
Hemos definido un bloque condicional para mostrar el enlace de Perfil y Cerrar sesión si el usuario esta autenticado.
Hemos definido un bloque condicional para mostrar los enlaces de Iniciar sesión y Registrarse si el usuario no esta autenticado.

Importante:
Para poder definir estos bloques condicionales, es necesario que el usuario este autenticado y que el modelo User tenga las propiedades is_collaborator, is_admin y is_registered.
En caso de querer mostrar más enlaces de acuerdo al tipo de usuario, se pueden definir más bloques condicionales.
Tener en cuenta que estas verificaciones son a nivel de plantilla, por lo que se recomienda hacer las verificaciones a nivel de view o middleware para mayor seguridad.
-->