blog_django/apps/post/urls.py
# blog_django/apps/post/urls.py
from django.urls import path
import apps.post.views as views
app_name = 'post'

urlpatterns = [
# Como cada post tiene un uuid, deberiamos usar un slug en lugar de el uuid como parametro
# Un slug es una cadena de texto que identifica de manera unica un recurso
# Pero a diferencia de un uuid, un slug es mas facil de recordar y de escribir
# En este caso, un post podria tener un slug que sea el titulo del post
# TODO: Cambiar para recibir un parametro de tipo <slug:slug>
    path('posts/', views.PostListView.as_view(), name="post_list"),
    path('posts/create', views.PostCreateView.as_view(), name="post_create"),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(),
    name="post_detail"),
    path('posts/<slug:slug>/update', views.PostUpdateView.as_view(),
    name="post_update"),
    path('posts/<slug:slug>/delete', views.PostDeleteView.as_view(),
    name="post_delete"),
]

"""
post_list: URL para listar los posts.
post_create: URL para crear un nuevo post.
post_detail: URL para ver un post en detalle.
post_update: URL para actualizar un post.
post_delete: URL para eliminar un post.
"""

#TODO: en admin, crear post

blog_django/blog_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog_django.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
path('', include('apps.user.urls')),
path('', include('apps.post.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    # Sirviendo archivos estáticos
    urlpatterns += static(settings.STATIC_URL,      document_root=settings.STATIC_ROOT)
    # Sirviendo archivos media
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_django/apps/post/models.py
from django.db import models
import uuid
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
import os


# Create your models here.
class Post(models.Model):
    id= models.UUIDField(primary_key=True, default=uuid.uuid4, editable= False)
    title= models.CharField(max_length=200)
    slug= models.SlugField(unique = True, max_length=200, blank= True)
    content= models.TextField(max_length=10000)
    author= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    creation_date= models.DateTimeField(default=timezone.now)
    modification_date= models.DateField(auto_now= True)
    allow_comments= models.BooleanField(default= True)

    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True, blank=True, related_name='posts')


    def __str__(self):
        return self.title
    
    @property
    #TODO definir comments
    def amount_comments(self):
        return self.comments.count()

    @property
    #TODO definir imagenes
    def amount_images(self):
        return self.images.count()


    
    def save(self,*args, **kwargs):
        if not self.slug:
            self.slug = self.generate_unique_slug()
        super().save(*args, **kwargs)
        
        if not self.images.exists():
            PostImage.objects.create(post=self, image='post/default/post_default.png')

        #TODO definir imagenes portada
    
    def generate_unique_slug(self):
        #tenemos este titulo par el post 1
        #tenemos-este-titulo-para-el-post-1  ----> para no dejar espacio en las urls
        slug = slugify(self.title)
        unique_slug = slug
        num = 1

        while Post.objects.filter(slug= unique_slug).exists():
            unique_slug=  f"{slug}-{num}"
            num += 1

        return unique_slug    


# blog_django/apps/post/models.py
def get_image_filename(instance, filename):
    post_id = instance.post.id
    images_count = instance.post.images.count()
    base_filename, file_extension = os.path.splitext(filename) # esto se llama unpacking (desempaquetado)
    new_filename = f"post_{post_id}_cover_{images_count + 1}{file_extension}"
    return os.path.join('post/cover/', new_filename)

class PostImage (models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=get_image_filename, default='post/default/post_default.png')
    active =  models.BooleanField(default=True)



    def __str__(self):
        return f"PostImage {self.id}"

#TODO imagen cover.png default post en carpeta cover
#Imagen de avatar en .png
#TODO realizar migraciones(tabla post image)



#TODO crear nueva app comnetarios para definirlos a parte
#TODO definir portada (portrait image_file)

class Comment(models.Model):
    id= models.UUIDField(primary_key=True, default=uuid.uuid4, editable= False)
    content= models.TextField(max_length=500)
    creation_date= models.DateTimeField(auto_now_add=True)
    author= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    post= models.ForeignKey(Post, on_delete= models.CASCADE, related_name="comments")

    #TODO terminar de definir funcion
    def __str__(self):
        return self.content
    

class Category (models.Model):
    id =  models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='category_posts')

blog_django/apps/post/forms.py
from django import forms
from apps.post.models import Post, PostImage

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'allow_comments')

class NewPostForm(PostForm):
    image = forms.ImageField(required=False)
    
    def save(self, commit=True):
        # Guardar el post pero no aún en la base de datos ya que necesitamos el id del post para la imagen
        post = super().save(commit=False)
        if commit:
            post.save() # Guardar el post
            if self.cleaned_data['image']:
                PostImage.objects.create(post=post, image=self.cleaned_data['image']) # Creamos la imagen
        return post
    

class UpdatePostForm(PostForm):
    image = forms.ImageField(required=False)
    
    def __init__(self, *args, **kwargs):
        # Obtenemos las imágenes activas del post que se quiere actualizar
        self.active_images = kwargs.pop('active_images', None)
        super(UpdatePostForm, self).__init__(*args, **kwargs)
        
        if self.active_images:
            for image in self.active_images:
                # keep_image_1, keep_image_2, ... etc es el nombre del campo que se creará en el formulario para mantener la imagen activa
                field_name = f"keep_image_{image.id}"
                self.fields[field_name] = forms.BooleanField(required=False, initial=True, label=f"Mantener {image}")
    
    def save(self, commit=True):
        post = super().save(commit=False)
        if commit:
            post.save()
            if self.cleaned_data['image']: # Si el usuario sube una nueva imagen
                PostImage.objects.create(post=post, image=self.cleaned_data['image'])

            if self.active_images: # Si hay imágenes activas y se quiere mantener alguna
                for image in self.active_images:
                    if not self.cleaned_data.get(f"keep_image_{image.id}", True): image.delete() # Eliminar la imagen si el usuario no la quiere mantener, checkboxes desmarcados
        return post
    

#En este formulario, definimos el formulario UpdatePostForm que hereda de PostForm y agrega un campo image de tipo forms.ImageField.

# Definimos el método __init__ para obtener las imágenes activas del post que se quiere actualizar y crear un campo en el formulario para mantener la imagen activa.

# Definimos el método save para guardar el post y las imágenes, y eliminar las imágenes que el usuario no quiere mantener.

# Nota: Para poder mantener las imágenes activas, es necesario definir un campo active de tipo BooleanField en el modelo PostImage que nos permita saber si la imagen esta activa o no.

blog_django/apps/post/views.py
# blog_django/apps/post/views.py

from django.views.generic import TemplateView, ListView, CreateView, DetailView, DeleteView, UpdateView
from apps.post.models import Post, PostImage
from apps.post.forms import NewPostForm, UpdatePostForm
from django.urls import reverse, reverse_lazy
from django.conf import settings

# TODO: Cambiar TemplateView por DetailView para que se pueda ver el detalle de un post

class PostListView(ListView):
    model =  Post
    template_name = 'post/post_list.html'
    context_object_name=  'posts'



class PostCreateView(CreateView):
    model = Post
    form_class = NewPostForm
    template_name = 'post/post_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        post = form.save()
        
        images = self.request.FILES.getlist('images')
        
        if images:
            for image in images:
                PostImage.objects.create(post=post, image=image)
        else:
            PostImage.objects.create(post=post, image=settings.DEFAULT_POST_IMAGE)
            
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('post:post_detail', kwargs={'slug': self.object.slug})


class PostDetailView(DetailView):
    template_name = 'post/post_detail.html'
    model = Post
    context_object_name = 'post'

    #Nota: Para poder obtener las imágenes del post, es necesario definir una relación ForeignKey en el modelo PostImage que haga referencia al modelo Post y un campo active que nos permita saber si la imagen esta activa o no, en este caso, se ha definido un campo active de tipo BooleanField en el modelo PostImage. Ademas podemos acceder a través de self.object.images ya que hemos definido una relación related_name='images' en el modelo PostImage.

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtener todas las imagenes activas del post
        active_images = self.object.images.filter(active= True)
        context['active_images'] = active_images
        return context
    


class PostUpdateView(UpdateView):
    model = Post
    form_class = UpdatePostForm
    template_name = 'post/post_update.html'
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['active_images'] = self.get_object().images.filter(active=True) # Pasamos las imágenes activas
        return kwargs
    
    def form_valid(self, form):
        post = form.save(commit=False)
        active_images = form.active_images
        keep_any_image_active = False
        
        # Manejo de las imágenes activas
        if active_images:
            for image in active_images:
                field_name = f"keep_image_{image.id}"
                # Si el checkbox no está marcado, eliminamos la imagen
                if not form.cleaned_data.get(field_name, True):
                    image.active = False
                    image.save()
                else:
                    keep_any_image_active = True
                    
        # Manejo de las nuevas imágenes subidas
        images = self.request.FILES.getlist('images')
        if images:
            for image in images:
                PostImage.objects.create(post=post, image=image)
        # Si no se desea mantener ninguna imagen activa y no se subieron nuevas imágenes, se agrega una imagen por defecto
        
        if not keep_any_image_active and not images:
            PostImage.objects.create(post=post, image=settings.DEFAULT_POST_IMAGE)
        post.save() # Guardar el post finalmente
        return super().form_valid(form)
    
    def get_success_url(self):
        # El reverse_lazy es para que no se ejecute hasta que se haya guardado el post
        return reverse_lazy('post:post_detail', kwargs={'slug': self.object.slug})


class PostDeleteView(DeleteView):
    template_name = 'post/post_delete.html'
    model = Post
    success_url = reverse_lazy('post:post_list') # Redirecciona a la url
    # definida en el archivo urls.py con el nombre post_list


#mportante: En el método form_valid, se manejan las imágenes activas y las nuevas imágenes subidas por el usuario, y se guarda el post finalmente.

blog_django/templates/post/post_create.html
<!-- blog_django\templates\post\post_create.html -->
{% extends 'layouts/post_layout.html' %}
{% block title %}Post | BLOG IA{% endblock title %}
{% block content %}
<h2>Crear nuevo post</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="flex flex-col gap-4">
        <p class="flex flex-col">{{ form.title.label_tag }} {{ form.title }}</p>
        <p class="flex flex-col">
            <label for="id_content">Contenido:</label> {{ form.content }}
        </p>
        <p>{{ form.allow_comments.label_tag }} {{ form.allow_comments }}</p>
        <p><input type="file" name="images" multiple /></p>
    </div>
    <button type="submit" class="bg-blue-500 text-white p-2 rounded-lg">
        Crear Post
    </button>
</form>
{% endblock content %}

<!--En esta plantilla se ha definido un formulario que permite crear un nuevo post.
Se ha definido un campo para el título, un campo para el contenido, un campo para permitir comentarios, y un campo para subir imágenes.
Importante: El atributo enctype="multipart/form-data" es necesario para poder subir archivos.-->

blog_django/templates/post/post_delete.html
{% extends 'layouts/post_layout.html' %}

{% block title %}BORRAR Post | BLOG IA{% endblock title %}

{% block content %}
<h2>¿Estás seguro de que deseas eliminar este post?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
</form>

<a href="{% url 'post:post_detail' slug=object.slug %}">Cancelar</a>
{% comment %} <a href="javascript:history.back()">Cancelar</a> {% endcomment %}
{% endblock content %}

<!--En esta plantilla se ha definido un formulario para eliminar un post.
Se ha definido un botón para confirmar la eliminación del post y un enlace para cancelar la acción.
Nota: El atributo method="post" es necesario para poder enviar la petición de eliminación.
Importante: En caso de querer redirigir a la vista anterior, se puede usar el enlace comentado en la
plantilla.-->

blog_django/templates/post/post_detail.html
<!-- blog_django/templates/post/post_detail.html -->
{% extends 'layouts/post_layout.html' %}
{% block title %}Post | BLOG IA{% endblock title %}
{% block content %}
{% if active_images %}
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
    {% for image in active_images %}
    <img src="{{ image.image.url }}" alt="Portada del post" class="w-[400px]
    object-cover aspect-[16/9]" />
    {% endfor %}
</div>
{% endif %}
<h3 class="text-2xl uppercase font-bold">{{ post.title }}</h3>
<p>{{ post.content }}</p>
<p>Publicado por: <strong class="font-bold">{{ post.author.username }}</strong>
</p>
<p>Fecha de publicación: {{ post.creation_date }}</p>
<p>Comentarios permitidos: {{ post.allow_comments|yesno:"Si,No" }}</p>
<div class="flex mt-8 gap-4">
    <a class="bg-blue-500 text-white p-2 rounded-lg" href="{% url 'post:post_update' slug=post.slug %}">Editar post</a>
    <a class="bg-red-500 text-white p-2 rounded-lg" href="{% url 'post:post_delete' slug=post.slug %}">Eliminar post</a>
</div>
{% endblock content %}

<!--En esta plantilla se ha definido la estructura para ver un post en detalle.
Se ha definido el título, el contenido, el autor, la fecha de publicación, si permite comentarios, y dos
botones para editar y eliminar el post.-->

<!--En este bloque, se ha definido un grid para mostrar las imágenes del post.
Se ha definido un ciclo for para recorrer las imágenes y mostrarlas en la plantilla.
Nota: Para poder mostrar las imágenes del post, es necesario definir un campo image de tipo
ImageField en el modelo PostImage que nos permita almacenar la imagen, para que luego podamos
obtener la URL de la misma.-->

blog_django/templates/post/post_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Layout</title>
</head>
<body>
    
</body>
</html>

blog_django/templates/post/post_list.html
{% extends 'layouts/post_layout.html' %}
{% block title %}Post | BLOG IA{% endblock title %}
{% block content %}
<div class="grid grid-cols-1 gap-6">
    {% for post in object_list %}
    <div class="bg-gray-800 text-white rounded-2xl p-6">
        <h3 class="text-2xl uppercase font-bold">{{ post.title }}</h3>
        <p>{{ post.content }}</p>
        <p>Publicado por: <strong class="font-bold">{{ post.author.username }}
            </strong></p>
        <p>Fecha de publicación: {{ post.creation_date }}</p>
        <p>Comentarios permitidos: {{ post.allow_comments|yesno:"Si,No" }}</p>
        <div class="flex gap-2 mt-8">
            <a class="bg-red-500 text-white p-2 rounded-lg" href="{% url 'post:post_detail' slug=post.slug %}">Ver
                post</a>
            <a class="bg-red-500 text-white p-2 rounded-lg" href="{% url 'post:post_delete' slug=post.slug %}">Eliminar
                post</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

<!--En esta plantilla se ha definido la estructura para listar los posts.
Se ha definido el título, el contenido, el autor, la fecha de publicación, si permite comentarios, y dos
botones para ver y eliminar el post.-->

blog_django/templates/post/post_update.html
{% extends 'layouts/post_layout.html' %}

{% block title %}ACTUALIZAR Post | BLOG IA{% endblock title %}

{% block content %}
<h2>Actualizar: {{ form.instance.title }}</h2>


<form method="post" enctype="multipart/form-data" class="flex flex-col justify-center items-start w-[400px] gap-4">
  {% csrf_token %}

  <div class="flex flex-col">{{ form.title.label_tag }} {{ form.title }}</div>
  <div class="flex flex-col">
    {{ form.content.label_tag }} {{ form.content }}
  </div>

  <div class="flex gap-4">
    {{ form.allow_comments.label_tag }} {{ form.allow_comments }}
  </div>

  <h3>Imágenes cargadas</h3>

  <div class="flex flex-col gap-4">
    {% for active_img in form.active_images %}
    {% comment %} <p>{{ active_img.id }}</p> {% endcomment %}
    {% comment %} <p>{{ active_img.post }}</p> {% endcomment %}
    {% comment %} <p>{{ active_img.post.author }}</p> {% endcomment %}
    {% comment %} <p>{{ active_img.image }}</p> {% endcomment %}
    {% comment %} <p>{{ active_img.image.url }}</p> {% endcomment %}
    {% comment %} <p>{{ active_img.active }}</p> {% endcomment %}
    {% comment %} <p>{{ active_img.creation_date }}</p> {% endcomment %}
    <p>
      <a href="{{ active_img.image.url }}" target="_blank">
        <img class="inline-flex w-[200px] aspect-[16/9] object-cover" src="{{ active_img.image.url }}"
          alt="Portada {{ active_img.id }} del post" />
      </a>
      <input type="checkbox" name="keep_image_{{ active_img.id }}" id="keep_image_{{ active_img.id }}" checked />
      <label for="keep_image_{{ active_img.id }}">Activa</label>
    </p>
    {% endfor %}
  </div>

  <h3>Cargar nuevas imágenes</h3>

  <input type="file" name="images" multiple />
  <div class="flex gap-2">
    <a href="{% url 'post:post_detail' slug=form.instance.slug %}"
      class="bg-red-500 text-white p-2 rounded-md">Cancelar</a>
    <button type="submit" class="bg-blue-500 text-white p-2 rounded-md">
      Guardar cambios
    </button>
  </div>
</form>

{% comment %} <a href="javascript:history.back()">Cancelar</a> {% endcomment %}
{% endblock content %}


<!--En esta plantilla se ha definido un formulario para actualizar un post.
Se ha definido un campo para el título, un campo para el contenido, un campo para permitir comentarios, un bloque para mostrar las imágenes activas del post, un campo para subir nuevas imágenes, y dos botones para cancelar y guardar los cambios.

Nota:
El atributo enctype="multipart/form-data" es necesario para poder subir archivos.
En caso de querer redirigir a la vista anterior, se puede usar el enlace comentado en la plantilla.

Importante: Se ha definido un ciclo for para recorrer las imágenes activas del post y mostrarlas en la plantilla, además se ha definido un campo keep_image_{{ active_img.id }} de tipo BooleanField para mantener la imagen activa.-->